//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int post_id { get; set; }
        public string homeAddress { get; set; }
        public string homePhone { get; set; }
        public string fullname { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
