//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int numberRoute { get; set; }
        public string direction { get; set; }
        public string firstPilot { get; set; }
        public string secondPilot { get; set; }
        public string stewardess { get; set; }
        public System.DateTime dateDeparture { get; set; }
        public Nullable<System.TimeSpan> timeDeparture { get; set; }
    }
}
